### ISSUE TITLE
icons not showing upon restart or opening of a new tab

### ISSUE THREAD

**Issue by drjkpalli** [devblackops/Terminal-Icons#86]
## Expected Behavior
upon opening o new tab or on restart of the terminal, icons should appear but they don't. works file when i do the following:
1. Install-Module -Name Terminal-Icons PSGallery
2. Import-Module -Name Terminal-Icons
3.   .$PROFILE

at this point, hitting 'ls' in this powershell shows all the icons as expected. but once i open a new tab, they dont appear upon typing ls in the terminal window.

## Your Environment

* Module version used: the latest auto-installed version
* Operating System and PowerShell version: windows 11, powershell version 5.1..........

**Comment by rafay99-epic** [comment]
## Request:
1. Bro can you share some screenshots.
2. $PROFILE will not open because a editior is not defined.
3. To use an editior use notepad or VS Code  for that enter the following commands.

## Opening Powershell Profile
Opening profile wilth VS code
`code $PROFILE`

Opening profile with notepad
`notepad $PROFILE`

## Powershell Config File
If you want a Powershell Config file you can use My config File:  https://gist.github.com/rafay99-epic/fa4a851aab87a9b0207e0a916ad42666

There are some programs that required to use this config file. The Program Name are described at the end of the script.

**Comment by drjkpalli** [comment]
Hi Abdul,
It only happens on the old built in windows power shell not the newer powershell. I installed the newer powershell and haven’t had that problem.

Regards
JK

**Comment by rafay99-epic** [comment]
That great... happy to hear ❤️

Regards 
AR
